/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/t5aQNeraXPf
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function ContactForm() {
  return (
    <div
      className="relative w-full h-screen bg-cover bg-center"
      style={{
        backgroundImage: "url(/bg.webp)",
      }}
    >
      <div className="absolute inset-0 bg-gray-700 bg-opacity-50" />
      <div className="absolute inset-0 flex items-center  justify-center p-4 ">
        <Card className="w-full max-w-4xl bg-white bg-opacity-90 p-6 shadow-lg shadow-gray-900/5 rounded-2xl">
          <CardHeader>
            <CardTitle className="text-center text-2xl">
              Job Consultancy Form
            </CardTitle>
            <CardDescription className="text-sm text-center">
              Submit your resume and job requirements, and our team will review
              your application within 24 hours.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="fullName">Full Name</Label>
              <Input id="fullName" placeholder="Enter your full name" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="Enter your email" type="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="phone">Phone Number</Label>
              <Input
                id="phone"
                placeholder="Enter your phone number"
                type="tel"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="phone">Job Requirements</Label>
              <Input
                id="phone"
                placeholder="Enter your job requirements"
                type="tel"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="resume">Upload Resume</Label>
              <Input id="resume" type="file" />
            </div>
          </CardContent>
          <CardFooter>
            <Button>Submit</Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  );
}
